#source scl_source enable devtoolset-7
source /opt/rh/devtoolset-7/enable
export COMMON_SET=1
export _condor_SCHEDD_HOST=sn-01.cr.cnaf.infn.it

export COMMONINSTALLDIR=/storage/gpfs_ams/ams/users/vvagelli/commonsw/install

export LD_LIBRARY_PATH=${COMMONINSTALLDIR}/BOOST_1.72.0/lib:$LD_LIBRARY_PATH

export LD_LIBRARY_PATH=${COMMONINSTALLDIR}/CURL_7.70.0/lib64:${LD_LIBRARY_PATH}
export PATH=${COMMONINSTALLDIR}/CURL_7.70.0/bin:${PATH}

export LD_LIBRARY_PATH=${COMMONINSTALLDIR}/CMAKE_3.17.0/lib:$LD_LIBRARY_PATH
export PATH=${COMMONINSTALLDIR}/CMAKE_3.17.0/bin:$PATH

export PATH=${COMMONINSTALLDIR}/GIT_2.26.0/bin:$PATH

export PATH=${COMMONINSTALLDIR}/QT_5.14.1/bin:$PATH
export LD_LIBRARY_PATH=${COMMONINSTALLDIR}/QT_5.14.1/lib:$LD_LIBRARY_PATH

export LD_LIBRARY_PATH=${COMMONINSTALLDIR}/XERCESC_3.2.2/lib:$LD_LIBRARY_PATH

export PATH=${COMMONINSTALLDIR}/HTOP_2.0.2/bin:${PATH}

source ${COMMONINSTALLDIR}/ROOT_6.20.00/bin/thisroot.sh

source ${COMMONINSTALLDIR}//GEANT4_10.04.p02/bin/geant4.sh

export GGS_SYS=${COMMONINSTALLDIR}/GGS_2.6.4
export PATH=$GGS_SYS/bin:$PATH
export LD_LIBRARY_PATH=$GGS_SYS/lib:$LD_LIBRARY_PATH
export ROOT_INCLUDE_PATH=$GGS_SYS/include:$ROOT_INCLUDE_PATH

export PATH=${COMMONINSTALLDIR}/VGM_4.5/bin:$PATH
export LD_LIBRARY_PATH=${COMMONINSTALLDIR}/VGM_4.5/lib64:$LD_LIBRARY_PATH

export EAINSTALLDIR=${COMMONINSTALLDIR}/EVENTANALYSIS_c5403642
export PATH=${EAINSTALLDIR}/bin:$PATH
export LD_LIBRARY_PATH=${EAINSTALLDIR}/lib:$LD_LIBRARY_PATH
export EA_PLUGIN_PATH=${EAINSTALLDIR}/plugin/:$EA_PLUGIN_PATH
